name = "K-EXAONE-2.0-750B-A37B"
description = "Frontier-scale multilingual language model developed by LG AI Research"
release_date = "2026-08-06"
last_updated = "2026-08-11"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = true

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "toggle"

[cost]
input = 0.6
output = 2.4
cache_read = 0.12

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]
